### PR TITLE
performance improvements

### PR DESCRIPTION
**Pull request by subes**
I did some benchmarks when using the library and incorporated my improvements. Hope you like them. :)

### CODE REVIEW

**Comment by vst** [comment]
Sure. Took a glance at it. Looks nice!

Will check, merge and make a new release soonest possible.

**Comment by subes** [comment]
not happening, will keep the fork

**Comment by vst** [comment]
Sorry for overlooking this.

Host application is still working in production using this library and I'd rather not break it. But let me know how you would like to proceed.

**Comment by subes** [comment]
Well my changes just improve performance, don't change anything on the functionality. I was using jenetics for a while but switching back to jdeoptim because of the better performance. I might want to implement some more features in my fork as part of my research. Though will see.

**Pull request closed without merging**
